//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TodoMVC.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class TodoList
    {
        public int ID { get; set; }
        public string UserName { get; set; }
        public string TodoTopic { get; set; }
        public bool Status { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> FinishTime { get; set; }
        public bool ShowStatus { get; set; }
    }
}
